"""Updated Vector Size for category embedding

Revision ID: 375a78675709
Revises: 5963204f1eca
Create Date: 2025-11-05 13:48:11.409428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '375a78675709'
down_revision: Union[str, None] = '5963204f1eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'categoryEmbedding',
               existing_type=Vector(dim=1500),
               type_=Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'categoryEmbedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=1500),
               existing_nullable=True)
    # ### end Alembic commands ###
