"""updated dimensions

Revision ID: 712fde8b83e8
Revises: f6f1fc31d59a
Create Date: 2025-11-05 19:54:33.033226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '712fde8b83e8'
down_revision: Union[str, None] = 'f6f1fc31d59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_embedding_cosine', table_name='Category', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('Interest', 'interestEmbedding',
               existing_type=Vector(dim=1500),
               type_=Vector(dim=768),
               existing_nullable=True)
    op.drop_index('ix_interest_embedding_cosine', table_name='Interest', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('News', 'Embedding',
               existing_type=Vector(dim=1500),
               type_=Vector(dim=768),
               existing_nullable=True)
    op.drop_index('ix_news_embedding_cosine', table_name='News', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_news_embedding_cosine', 'News', ['Embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('News', 'Embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=1500),
               existing_nullable=True)
    op.create_index('ix_interest_embedding_cosine', 'Interest', ['interestEmbedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('Interest', 'interestEmbedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=1500),
               existing_nullable=True)
    op.create_index('ix_category_embedding_cosine', 'Category', ['categoryEmbedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
