"""Created index for Interest

Revision ID: 777ee48aad50
Revises: 7d13b5a44a94
Create Date: 2025-10-28 21:30:31.257429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777ee48aad50'
down_revision: Union[str, None] = '7d13b5a44a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Interest_interestEmbedding'), 'Interest', ['interestEmbedding'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Interest_interestEmbedding'), table_name='Interest')
    # ### end Alembic commands ###
