"""Table Creation

Revision ID: 7d13b5a44a94
Revises: 4b4a7560d895
Create Date: 2025-10-28 20:08:05.561981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7d13b5a44a94'
down_revision: Union[str, None] = '4b4a7560d895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('categoryEmbedding', Vector(dim=1500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Category_categoryEmbedding'), 'Category', ['categoryEmbedding'], unique=False)
    op.create_table('Interest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interestEmbedding', Vector(dim=1500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Password',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('News',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('publicationDate', sa.DateTime(), nullable=True),
    sa.Column('aiGeneratedText', sa.String(), nullable=True),
    sa.Column('Embedding', Vector(dim=1500), nullable=True),
    sa.Column('validationText', sa.String(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_News_Embedding'), 'News', ['Embedding'], unique=False)
    op.create_index(op.f('ix_News_aiGeneratedText'), 'News', ['aiGeneratedText'], unique=False)
    op.create_index(op.f('ix_News_validationText'), 'News', ['validationText'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passwordId'], ['Password.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passwordId')
    )
    op.create_table('Upvotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('newsId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['newsId'], ['News.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_Category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['Category.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_Interest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('interestId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interestId'], ['Interest.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_Interest')
    op.drop_table('User_Category')
    op.drop_table('Upvotes')
    op.drop_table('User')
    op.drop_index(op.f('ix_News_validationText'), table_name='News')
    op.drop_index(op.f('ix_News_aiGeneratedText'), table_name='News')
    op.drop_index(op.f('ix_News_Embedding'), table_name='News')
    op.drop_table('News')
    op.drop_table('Password')
    op.drop_table('Interest')
    op.drop_index(op.f('ix_Category_categoryEmbedding'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
