"""Removed indexes from embedding columns

Revision ID: f6f1fc31d59a
Revises: ab9cdc62db31
Create Date: 2025-11-05 14:03:43.552095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f1fc31d59a'
down_revision: Union[str, None] = 'ab9cdc62db31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Category_categoryEmbedding', table_name='Category')
    op.drop_index('ix_Interest_interestEmbedding', table_name='Interest')
    op.drop_index('ix_News_Embedding', table_name='News')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_News_Embedding', 'News', ['Embedding'], unique=False)
    op.create_index('ix_Interest_interestEmbedding', 'Interest', ['interestEmbedding'], unique=False)
    op.create_index('ix_Category_categoryEmbedding', 'Category', ['categoryEmbedding'], unique=False)
    # ### end Alembic commands ###
