environment: "dev"
update_interval: 72
feeds:
  - "https://ct24.ceskatelevize.cz/rss/tema/vyber-redakce-84313"
  - "https://www.irozhlas.cz/rss/irozhlas"
  - "https://www.ceskenoviny.cz/sluzby/rss/zpravy.php"
  - "https://www.seznamzpravy.cz/rss"
  - "https://www.novinky.cz/rss"
  - "https://servis.idnes.cz/rss.aspx?"
  - "https://www.aktualne.cz/rss/"
  - "https://www.denik.cz/rss/zpravy.html"
  - "https://servis.lidovky.cz/rss.aspx"
  - "https://cnn.iprima.cz/rss"
  - "https://www.e15.cz/rss"
  - "https://www.forum24.cz/feed/"
  - "https://www.reflex.cz/rss"
  - "https://www.blesk.cz/rss"
  - "https://www.super.cz/rss"